version: 2.1

jobs:
  run-archiveteam:
    docker:
      - image: cimg/base:current
    steps:
      - setup_remote_docker:
          version: 29.6.2
      - run:
          name: "Lancer ArchiveTeam Reddit Grab"
          command: |
            docker run -d --name archiveteam \
              --label=com.centurylinklabs.watchtower.enable=true \
              --restart=unless-stopped \
              atdr.meo.ws/archiveteam/nihnlmdigitalcollections-grab \
              --concurrent 20 Exorcism
            docker logs --tail 0 -f archiveteam

workflows:
  archive-workflow:
    jobs:
      - run-archiveteam
