version: 2.1

jobs:
  run-archiveteam:
    docker:
      - image: cimg/base:current
    steps:
      - setup_remote_docker:
          version: docker29
      - run:
          name: "Lancer ArchiveTeam Reddit Grab"
          command: |
            docker run -d --name archiveteam \
              --label=com.centurylinklabs.watchtower.enable=true \
              --restart=unless-stopped \
              atdr.meo.ws/archiveteam/sinavideo-grab \
              --concurrent 6 Exorcism
            docker run -d --name archiveteam1 \
              --label=com.centurylinklabs.watchtower.enable=true \
              --restart=unless-stopped \
              atdr.meo.ws/archiveteam/bitbucket2-grab \
              --concurrent 1 Exorcism
            docker logs --tail 0 -f archiveteam && docker logs --tail 0 -f archiveteam1

workflows:
  archive-workflow:
    jobs:
      - run-archiveteam
